# Tarea día 8
**Programación I**

In [1]:
import numpy as np
import random

## Ejercicio 1

Cree una matriz que contenga ceros. Rellene la mitad de ellos aleatoriamente con unos.

In [2]:
filas=5
columnas=7
tamaño=int(filas*columnas)
mitad=int(tamaño/2-1)
a=np.arange(tamaño)
a[0:mitad]=1
a[mitad:]=0
np.random.shuffle(a)
b=a.reshape(filas,columnas)
print(b)

[[0 1 0 1 0 0 1]
 [1 1 1 0 0 0 1]
 [0 1 1 0 0 1 0]
 [0 0 0 1 1 0 1]
 [0 1 1 0 0 0 1]]


## Ejercicio 2
Cree dos matrices de dimensiones $(5,2)$. La primera rellena de ceros y la siguiente de unos. 
1.	Convierta las matrices en vectores columna. 
2.	Apile ambos vectores a lo largo de una tercera dimensión. 
3.	Con las matrices originales, conviértalas en vectores fila y concaténelos verticalmente. 


In [3]:
#1.Convierta las matrices en vectores columna. 
m=5
n=2
a=np.zeros([m,n])
b=np.ones([m,n])
c=a.reshape(10,1)
d=b.reshape(10,1)

In [4]:
c

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [5]:
d

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [6]:
#2.Apile ambos vectores a lo largo de una tercera dimensión. 
m=5
n=2
a=np.zeros([m,n])
b=np.ones([m,n])
c=a.reshape(1,10)
d=b.reshape(1,10)
c=np.dstack((c,d))
c

array([[[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]]])

In [7]:
#Instrucción para obtener la dimensión del arreglo.
#En este caso se esta demostrando que la apilación de los vectores
#a y b, apilados en c estan en una tercera dimensión.
c.ndim

3

In [8]:
#3.Con las matrices originales, conviértalas en
#  vectores fila y concaténelos verticalmente. 
m=5
n=2
a=np.zeros([m,n])
b=np.ones([m,n])
c=a.reshape(1,10)
d=b.reshape(1,10)
np.concatenate((c, d), axis=0)
#Al usar concatenate axis=0 el ordenamiento es de arriba hacia abajo

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [9]:
#3.Alternativamente se puede usar v stack
m=5
n=2
a=np.zeros([m,n])
b=np.ones([m,n])
c=a.reshape(1,10)
d=b.reshape(1,10)
np.vstack((c, d))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## Ejercicio 3

Dada la función $f(x,y,z) = 2x +3y + z^2$
1.	Genere una matriz con números aleatorios, donde cada columna sea una variable. 
2.	Evalúe la matriz anterior en la función. El resultado debe ser una vector columna. 

In [10]:
def f(x,y,z):
    return 2*x+3*y+z**2

#1.Genere una matriz con números aleatorios, donde cada columna 
#  sea una variable.

ev=10
a=np.random.randint(100,size=(ev,3))

#2.Evalúe la matriz anterior en la función. El resultado debe ser 
#  una vector columna. 

x=a[:,0]
y=a[:,1]
z=a[:,2]

f(x,y,z).reshape(-1,1)


array([[5163],
       [1693],
       [4147],
       [7756],
       [3012],
       [1040],
       [6116],
       [1954],
       [5640],
       [1959]])

In [11]:
lambda x,y,z: 2*x+3*y+z**2
np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

## Ejercicio 4

Suponga que dentro de un cuadrado de lado 50 cm, hay un cuadrado de 20cm. Ambos cuadrados comparten centro. Estime el área del cuadrado interno por método Monte Carlo. [Consulte Aquí]( http://mathonweb.com/entrtain/monte/t_monte.htm)

In [12]:
a=50
b=a
c_e=np.random.choice(2, a*b).reshape(a,b)
c_i=c_e[15:35,15:35]
proporcion=c_i.sum()/c_e.sum()
area_c_i=a*b*proporcion
area_c_i

396.19651347068145

## Ejercicio 5

### *Tarea*

1. De las siguientes secciones, escoger 73 funciones de NumPy y mostrar su utilización en un ejemplo.

    - [Array creation routines](https://numpy.org/devdocs/reference/routines.array-creation.html)

    - [Array manipulation routines](https://numpy.org/devdocs/reference/routines.array-manipulation.html)

    - [Binary operations](https://numpy.org/devdocs/reference/routines.bitwise.html)

    - [String operations](https://numpy.org/devdocs/reference/routines.char.html)
    

2. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo binario `.npy` y `.npz`:

    - [NumPy binary files (NPY, NPZ)](https://numpy.org/devdocs/reference/routines.io.html#numpy-binary-files-npy-npz)
    
3. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo de texto `.txt`:

    - [NumPy Text files](https://numpy.org/devdocs/reference/routines.io.html#text-files)    
    
4. Crear una función llamada `estimacionMCO` que lea un archivo CSV con 7 columnas, que corresponden a las variables $(x_{1i}, \ldots, x_{6i})$ y $y_i$. 
    - La función debe computar matricialmente los parámetros del modelo de regresión lineal: $y = X\beta$. 
    - Estos parámetros deben ser devueltos como un arreglo de NumPy. 

    - Utilice la función de lectura de archivos de NumPy.

# Array creation routines

## Ones and zeros

### 1. numpy.empty
Crea un array del tamaño y tipo de dato especificado 
(si no se especifica, el tipo será float por defecto).

https://numpy.org/devdocs/reference/generated/numpy.empty.html#numpy.empty
 

In [13]:
np.empty([2, 2])

array([[2.11395428e-307, 3.44900538e-307],
       [2.33645657e-307, 1.61324306e-307]])

In [14]:
np.empty([2, 2], dtype=int)

array([[0, 0],
       [0, 0]])

### 2. numpy.empty_like
Acepta como primer argumento un objeto "semejante a un array" 
(puede ser una lista, una tupla, otro array...) cuyo tamaño y 
tipo de datos se replicarán en el array NumPy que se cree 
sin inicializar los valores.

https://numpy.org/devdocs/reference/generated/numpy.empty_like.html#numpy.empty_like

In [15]:
a = ([1,2,3], [4,5,6])
np.empty_like(a)

array([[1010497504,        600,          0],
       [         0,     131074,          0]])

In [16]:
a = np.array([[1., 2., 3.],[4.,5.,6.]])
np.empty_like(a)

array([[0., 0., 0.],
       [0., 0., 0.]])

### 3. numpy.eye
Devuelve un array de dos dimensiones con unos en la diagonal 
principal y ceros en el resto del array.

https://numpy.org/devdocs/reference/generated/numpy.eye.html#numpy.eye

In [17]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [18]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

### 4. numpy.identity
Devuelve un array cuadrado con unos en la diagonal principal 
y ceros en el resto del array.

https://numpy.org/devdocs/reference/generated/numpy.identity.html#numpy.identity

In [19]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 5. numpy.ones
Devuelve un array del tamaño y tipo indicados inicializando 
sus valores con unos.

https://numpy.org/devdocs/reference/generated/numpy.ones.html#numpy.ones

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.ones((5,), dtype=int)

array([1, 1, 1, 1, 1])

In [22]:
np.ones((2, 1))

array([[1.],
       [1.]])

In [23]:
s = (2,2)
np.ones(s)

array([[1., 1.],
       [1., 1.]])

### 6. numpy.ones_like
Acepta como primer argumento un objeto "semejante a un array" 
(puede ser una lista, una tupla, otro array...) cuyo tamaño y 
tipo de datos se replicarán en el array NumPy que se cree 
inicializándolos con unos.

https://numpy.org/devdocs/reference/generated/numpy.ones_like.html#numpy.ones_like

In [24]:
x = np.arange(6)
x = x.reshape((2, 3))
x

array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
np.ones_like(x)

array([[1, 1, 1],
       [1, 1, 1]])

In [26]:
y = np.arange(3, dtype=float)
y

array([0., 1., 2.])

In [27]:
np.ones_like(y)

array([1., 1., 1.])

### 7. numpy.zeros
Devuelve un array del tamaño y tipo indicados inicializando sus valores con ceros

https://numpy.org/devdocs/reference/generated/numpy.zeros.html#numpy.zeros


In [28]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [29]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [30]:
np.zeros((2, 1))

array([[0.],
       [0.]])

In [31]:
s = (2,2)
np.zeros(s)

array([[0., 0.],
       [0., 0.]])

In [32]:
np.zeros((2,), dtype=[('x', 'i4'), ('y', 'i4')]) 

array([(0, 0), (0, 0)], dtype=[('x', '<i4'), ('y', '<i4')])

### 8. numpy.zeros_like

Acepta como primer argumento un objeto "semejante a un array" (puede ser una lista, una tupla, otro array...) cuyo tamaño y tipo de datos se replicarán en el array NumPy que se cree inicializándolos con ceros.

https://numpy.org/devdocs/reference/generated/numpy.zeros_like.html#numpy.zeros_like

In [33]:
x = np.arange(6)
x = x.reshape((2, 3))
x

array([[0, 1, 2],
       [3, 4, 5]])

In [34]:
np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]])

In [35]:
y = np.arange(3, dtype=float)
y

array([0., 1., 2.])

In [36]:
np.zeros_like(y)

array([0., 0., 0.])

### 9. numpy.full
Permite crear un array de cierto tamaño y tipo rellenándolo con un valor concreto

https://numpy.org/devdocs/reference/generated/numpy.full.html#numpy.full

In [37]:
np.full((2, 2), np.inf)

array([[inf, inf],
       [inf, inf]])

In [38]:
np.full((2, 2), [1, 2])

array([[1, 2],
       [1, 2]])

### 10. numpy.full_like
Acepta como primer argumento un objeto "semejante a un array" (puede ser una lista, una tupla, otro array...) cuyo tamaño y tipo de datos se replicarán en el array NumPy que se cree inicializándolos con inicializándose con el valor que se indique.

https://numpy.org/devdocs/reference/generated/numpy.full_like.html#numpy.full_like

In [39]:
x = np.arange(6, dtype=int)
np.full_like(x, 1)

array([1, 1, 1, 1, 1, 1])

In [40]:
np.full_like(x, 0.1)

array([0, 0, 0, 0, 0, 0])

In [41]:
np.full_like(x, 0.1, dtype=np.double)

array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

In [42]:
np.full_like(x, np.nan, dtype=np.double)

array([nan, nan, nan, nan, nan, nan])

## From existing data

### 11. array
Crea un array a partir de un iterador.

https://numpy.org/devdocs/reference/routines.array-creation.html
https://www.interactivechaos.com/manual/tutorial-de-numpy/la-funcion-array

In [43]:
np.array([1, 2, 3])

array([1, 2, 3])

In [44]:
# Upcasting
np.array([1, 2, 3.0])

array([1., 2., 3.])

In [45]:
#More than one dimension
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [46]:
# Minimum dimensions 2:
np.array([1, 2, 3], ndmin=2)

array([[1, 2, 3]])

In [47]:
#Type provided:
np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [48]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i4'),('b','<i4')])
x['a']

array([1, 3])

In [49]:
#Creating an array from sub-classes:
np.array(np.mat('1 2; 3 4'))

array([[1, 2],
       [3, 4]])

In [50]:
np.array(np.mat('1 2; 3 4'), subok=True)

matrix([[1, 2],
        [3, 4]])

### 12. numpy.asarray
Convert the input to an array.

https://numpy.org/devdocs/reference/generated/numpy.asarray.html#numpy.asarray

In [51]:
#Convert a list into an array:
a = [1, 2]
np.asarray(a)

array([1, 2])

In [52]:
#Existing arrays are not copied:
a = np.array([1, 2])
np.asarray(a) is a

True

### 13. numpy.asmatrix
Interpret the input as a matrix.

Unlike matrix, asmatrix does not make a copy if the input is already a matrix or an ndarray. Equivalent to matrix(data, copy=False).

https://numpy.org/devdocs/reference/generated/numpy.asmatrix.html#numpy.asmatrix

In [53]:
x = np.array([[1, 2], [3, 4]])
m = np.asmatrix(x)
x[0,0] = 5
m

matrix([[5, 2],
        [3, 4]])

### 14. numpy.fromfunction
Construct an array by executing a function over each coordinate.

The resulting array therefore has a value fn(x, y, z) at coordinate (x, y, z).

https://numpy.org/devdocs/reference/generated/numpy.fromfunction.html#numpy.fromfunction

In [54]:
 np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [55]:
np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### 15. numpy.copy
Return an array copy of the given object.

https://numpy.org/devdocs/reference/generated/numpy.copy.html#numpy.copy


In [56]:
#This is equivalent to:
np.array(a, copy=True)  

array([1, 2])

In [57]:
#Create an array x, with a reference y and a copy z:
x = np.array([1, 2, 3])
y = x
z = np.copy(x)
#Note that, when we modify x, y changes, but not z:
x[0] = 10
x[0] == y[0]

True

In [58]:
x[0] == z[0]

False

### 16. numpy.core.records.fromarrays
Create a record array from a (flat) list of arrays

https://numpy.org/devdocs/reference/generated/numpy.core.records.fromarrays.html#numpy.core.records.fromarrays

In [59]:
x1=np.array([1,2,3,4])
x2=np.array(['a','dd','xyz','12'])
x3=np.array([1.1,2,3,4])
r = np.core.records.fromarrays([x1,x2,x3],names='a,b,c')
r

rec.array([(1, 'a', 1.1), (2, 'dd', 2. ), (3, 'xyz', 3. ), (4, '12', 4. )],
          dtype=[('a', '<i4'), ('b', '<U3'), ('c', '<f8')])

In [60]:
print(r[1])

(2, 'dd', 2.)


In [61]:
x1[1]=34
x1

array([ 1, 34,  3,  4])

In [62]:
r.a

array([1, 2, 3, 4])

### 17. numpy.mgrid
nd_grid instance which returns a dense multi-dimensional “meshgrid”.

https://numpy.org/devdocs/reference/generated/numpy.mgrid.html#numpy.mgrid

In [63]:
np.mgrid[0:5,0:5]

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [64]:
np.mgrid[0:5,0:5:,0:5]

array([[[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[2, 2, 2, 2, 2],
         [2, 2, 2, 2, 2],
         [2, 2, 2, 2, 2],
         [2, 2, 2, 2, 2],
         [2, 2, 2, 2, 2]],

        [[3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3]],

        [[4, 4, 4, 4, 4],
         [4, 4, 4, 4, 4],
         [4, 4, 4, 4, 4],
         [4, 4, 4, 4, 4],
         [4, 4, 4, 4, 4]]],


       [[[0, 0, 0, 0, 0],
         [1, 1, 1, 1, 1],
         [2, 2, 2, 2, 2],
         [3, 3, 3, 3, 3],
         [4, 4, 4, 4, 4]],

        [[0, 0, 0, 0, 0],
         [1, 1, 1, 1, 1],
         [2, 2, 2, 2, 2],
         [3, 3, 3, 3, 3],
         [4, 4, 4, 4, 4]],

        [[0, 0, 0, 0, 0],
         [1, 1, 1, 1, 1],
         [2, 2, 2, 2, 

In [65]:
np.mgrid[-1:1:5j]

array([-1. , -0.5,  0. ,  0.5,  1. ])

### 18. numpy.diag
Extract a diagonal or construct a diagonal array.

https://numpy.org/devdocs/reference/generated/numpy.diag.html#numpy.diag

In [66]:
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [67]:
np.diag(x)

array([0, 4, 8])

In [68]:
np.diag(x, k=1)

array([1, 5])

In [69]:
np.diag(x, k=-1)

array([3, 7])

In [70]:
np.diag(np.diag(x))

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

### 19.numpy.diagflat
Create a two-dimensional array with the flattened input as a diagonal.

https://numpy.org/devdocs/reference/generated/numpy.diagflat.html#numpy.diagflat

In [71]:
np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [72]:
np.diagflat([1,2], 1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

### 20. numpy.tri
An array with ones at and below the given diagonal and zeros 

https://numpy.org/devdocs/reference/generated/numpy.tri.html#numpy.trielsewhere.

In [73]:
np.tri(3, 5, 2, dtype=int)

array([[1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])

In [74]:
np.tri(3, 5, -1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

### 21. numpy.tril

Lower triangle of an array.
Return a copy of an array with elements above the k-th diagonal zeroed.

https://numpy.org/devdocs/reference/generated/numpy.tril.html#numpy.tril

In [75]:
np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)

array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

### 22. numpy.triu
Upper triangle of an array.

Return a copy of a matrix with the elements below the k-th diagonal zeroed.

https://numpy.org/devdocs/reference/generated/numpy.triu.html#numpy.triu

In [76]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

# Array manipulation routines

https://code-examples.net/en/docs/numpy~1.17/routines.array-manipulation

## Basic operations

### 23. numpy.shape
Return the shape of an array

https://numpy.org/devdocs/reference/generated/numpy.shape.html#numpy.shape

In [77]:
np.shape(np.eye(3))

(3, 3)

In [78]:
np.shape([[1, 2]])

(1, 2)

In [79]:
np.shape([0])

(1,)

In [80]:
np.shape(0)

()

In [81]:
a = np.array([(1, 2), (3, 4)], dtype=[('x', 'i4'), ('y', 'i4')])
np.shape(a)

(2,)

In [82]:
a.shape

(2,)

### 24. numpy.reshape
Gives a new shape to an array without changing its data.

https://numpy.org/devdocs/reference/generated/numpy.reshape.html#numpy.reshape

In [83]:
a = np.zeros((10, 2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [84]:
# A transpose makes the array non-contiguous
b = a.T
b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [85]:
c = b.view()
c

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [86]:
#c.shape = (20)
'''
---------------------------------------------------------------------------
AttributeError  Traceback (most recent call last)
<ipython-input-84-035e79ad6f6a> in <module>
----> 1 c.shape = (20)

AttributeError: incompatible shape for a non-contiguous array
'''

'\n---------------------------------------------------------------------------\nAttributeError  Traceback (most recent call last)\n<ipython-input-84-035e79ad6f6a> in <module>\n----> 1 c.shape = (20)\n\nAttributeError: incompatible shape for a non-contiguous array\n'

In [87]:
# The order keyword gives the index ordering both for fetching 
#the values from a, and then placing the values into the output array.
#For example, let’s say you have an array:
a = np.arange(6).reshape((3, 2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [88]:
# You can think of reshaping as first raveling the array 
#(using the given index order), then inserting the elements from 
#the raveled array into the new array using the same kind of index 
#ordering as was used for the raveling.

np.reshape(a, (2, 3)) # C-like index ordering

array([[0, 1, 2],
       [3, 4, 5]])

In [89]:
np.reshape(np.ravel(a), (2, 3)) # equivalent to C ravel then C reshape

array([[0, 1, 2],
       [3, 4, 5]])

In [90]:
np.reshape(a, (2, 3), order='F') # Fortran-like index ordering

array([[0, 4, 3],
       [2, 1, 5]])

In [91]:
np.reshape(np.ravel(a, order='F'), (2, 3), order='F')

array([[0, 4, 3],
       [2, 1, 5]])

In [92]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
np.reshape(a, 6)

array([1, 2, 3, 4, 5, 6])

In [94]:
np.reshape(a, 6, order='F')

array([1, 4, 2, 5, 3, 6])

In [95]:
np.reshape(a, (3,-1))   # the unspecified value is inferred to be 2

array([[1, 2],
       [3, 4],
       [5, 6]])

### 25. numpy.ravel
Return a contiguous flattened array.

A 1-D array, containing the elements of the input, is returned. A copy is made only if needed.

https://numpy.org/devdocs/reference/generated/numpy.ravel.html#numpy.ravel

In [96]:
# It is equivalent to reshape(-1, order=order).
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
np.ravel(x)

array([1, 2, 3, 4, 5, 6])

In [98]:
x.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [99]:
np.ravel(x, order='F')

array([1, 4, 2, 5, 3, 6])

In [100]:
#When order is ‘A’, it will preserve the array’s ‘C’ or ‘F’ ordering:
np.ravel(x.T)

array([1, 4, 2, 5, 3, 6])

In [101]:
np.ravel(x.T, order='A')

array([1, 2, 3, 4, 5, 6])

In [102]:
#When order is ‘K’, it will preserve orderings that are 
#neither ‘C’ nor ‘F’, but won’t reverse axes:
a = np.arange(3)[::-1]; a

array([2, 1, 0])

In [103]:
a.ravel(order='C')

array([2, 1, 0])

In [104]:
a.ravel(order='K')

array([2, 1, 0])

In [105]:
a = np.arange(12).reshape(2,3,2).swapaxes(1,2); a

array([[[ 0,  2,  4],
        [ 1,  3,  5]],

       [[ 6,  8, 10],
        [ 7,  9, 11]]])

In [106]:
a.ravel(order='C')

array([ 0,  2,  4,  1,  3,  5,  6,  8, 10,  7,  9, 11])

In [107]:
a.ravel(order='K')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### 26.numpy.ndarray.flat
Attribute

https://numpy.org/devdocs/reference/generated/numpy.ndarray.flat.html#numpy.ndarray.flat

In [108]:
x = np.arange(1, 7).reshape(2, 3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [109]:
x.flat[3]

4

In [110]:
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [111]:
x.T.flat[3]

5

In [112]:
type(x.flat)

numpy.flatiter

In [113]:
x.flat = 3; x

array([[3, 3, 3],
       [3, 3, 3]])

In [114]:
x.flat[[1,4]] = 1; x

array([[3, 1, 3],
       [3, 1, 3]])

### 27. numpy.ndarray.flatten
Method

https://numpy.org/devdocs/reference/generated/numpy.ndarray.flatten.html#numpy.ndarray.flatten

In [115]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [116]:
a.flatten()

array([1, 2, 3, 4])

In [117]:
a.flatten('F')

array([1, 3, 2, 4])

## Transpose-like operations

###  28. numpy.moveaxis
Move axes of an array to new positions.

Other axes remain in their original order.

https://numpy.org/devdocs/reference/generated/numpy.moveaxis.html#numpy.moveaxis

In [118]:
x = np.zeros((3, 4, 5))
x

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [119]:
np.moveaxis(x, 0, -1).shape

(4, 5, 3)

In [120]:
np.moveaxis(x, -1, 0).shape

(5, 3, 4)

### 29. numpy.rollaxis
Roll the specified axis backwards, until it lies in a given position.

https://numpy.org/devdocs/reference/generated/numpy.rollaxis.html#numpy.rollaxis

In [121]:
a = np.ones((3,4,5,6,7))
np.rollaxis(a, 3, 1).shape

(3, 6, 4, 5, 7)

In [122]:
np.rollaxis(a, 2).shape

(5, 3, 4, 6, 7)

In [123]:
np.rollaxis(a, 1, 4).shape

(3, 5, 6, 4, 7)

### 30. numpy.swapaxes
Interchange two axes of an array.

https://numpy.org/devdocs/reference/generated/numpy.swapaxes.html#numpy.swapaxes

In [124]:
x = np.array([[1,2,3]])
x

array([[1, 2, 3]])

In [125]:
np.swapaxes(x,0,1)

array([[1],
       [2],
       [3]])

In [126]:
x = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [127]:
np.swapaxes(x,0,2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

### 31. numpy.ndarray.T
The transposed array.

https://numpy.org/devdocs/reference/generated/numpy.ndarray.T.html#numpy.ndarray.T

In [128]:
x = np.array([[1.,2.],[3.,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [129]:
x.T

array([[1., 3.],
       [2., 4.]])

In [130]:
x = np.array([1.,2.,3.,4.])
x

array([1., 2., 3., 4.])

In [131]:
x.T

array([1., 2., 3., 4.])

### 32. numpy.transpose
Reverse or permute the axes of an array; returns the modified array.

For an array a with two axes, transpose(a) gives the matrix transpose.

In [132]:
x = np.arange(4).reshape((2,2))
x

array([[0, 1],
       [2, 3]])

In [133]:
np.transpose(x)

array([[0, 2],
       [1, 3]])

In [134]:
x = np.ones((1, 2, 3))
x

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [135]:
np.transpose(x, (1, 0, 2)).shape

(2, 1, 3)

## Changing number of dimensions

### 33. numpy.atleast_1d
Convert inputs to arrays with at least one dimension.

Scalar inputs are converted to 1-dimensional arrays, whilst higher-dimensional inputs are preserved.

https://numpy.org/devdocs/reference/generated/numpy.atleast_1d.html#numpy.atleast_1d

In [136]:
np.atleast_1d(1.0)

array([1.])

In [137]:
x = np.arange(9.0).reshape(3,3)
x

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [138]:
np.atleast_1d(x)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [139]:
np.atleast_1d(x) is x

True

In [140]:
np.atleast_1d(1, [3, 4])

[array([1]), array([3, 4])]

### 34. numpy.atleast_2d
View inputs as arrays with at least two dimensions.

https://numpy.org/devdocs/reference/generated/numpy.atleast_2d.html#numpy.atleast_2d

In [141]:
np.atleast_2d(3.0)

array([[3.]])

In [142]:
x = np.arange(3.0)
x

array([0., 1., 2.])

In [143]:
np.atleast_2d(x)

array([[0., 1., 2.]])

In [144]:
np.atleast_2d(x).base is x

True

In [145]:
 np.atleast_2d(1, [1, 2], [[1, 2]])

[array([[1]]), array([[1, 2]]), array([[1, 2]])]

### 35. numpy.atleast_3d
View inputs as arrays with at least three dimensions.

https://numpy.org/devdocs/reference/generated/numpy.atleast_3d.html#numpy.atleast_3d

In [146]:
np.atleast_3d(3.0)

array([[[3.]]])

In [147]:
x = np.arange(3.0)
x

array([0., 1., 2.])

In [148]:
np.atleast_3d(x).shape

(1, 3, 1)

In [149]:
x = np.arange(12.0).reshape(4,3)
x

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [150]:
np.atleast_3d(x)

array([[[ 0.],
        [ 1.],
        [ 2.]],

       [[ 3.],
        [ 4.],
        [ 5.]],

       [[ 6.],
        [ 7.],
        [ 8.]],

       [[ 9.],
        [10.],
        [11.]]])

In [151]:
np.atleast_3d(x).shape

(4, 3, 1)

In [152]:
np.atleast_3d(x).base is x.base  # x is a reshape, so not base itself

True

In [153]:
for arr in np.atleast_3d([1, 2], [[1, 2]], [[[1, 2]]]):
    print(arr, arr.shape) 

[[[1]
  [2]]] (1, 2, 1)
[[[1]
  [2]]] (1, 2, 1)
[[[1 2]]] (1, 1, 2)


### 36. numpy.broadcast
Produce an object that mimics broadcasting.

https://numpy.org/devdocs/reference/generated/numpy.broadcast.html#numpy.broadcast

In [154]:
# Manually adding two vectors, using broadcasting:
x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])
b = np.broadcast(x, y)
b.shape

(3, 3)

In [155]:
out = np.empty(b.shape)
out

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [156]:
out.flat = [u+v for (u,v) in b]
out

array([[5., 6., 7.],
       [6., 7., 8.],
       [7., 8., 9.]])

In [157]:
#Compare against built-in broadcasting:
x + y

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

### 37. numpy.squeeze
Remove single-dimensional entries from the shape of an array.

https://numpy.org/devdocs/reference/generated/numpy.squeeze.html#numpy.squeeze

In [158]:
x = np.array([[[0], [1], [2]]])
x

array([[[0],
        [1],
        [2]]])

In [159]:
x.shape

(1, 3, 1)

In [160]:
np.squeeze(x).shape

(3,)

In [161]:
#np.squeeze(x, axis=1).shape
'''
Traceback (most recent call last):
...
ValueError: cannot select an axis to squeeze out which has size not equal to one
'''

'\nTraceback (most recent call last):\n...\nValueError: cannot select an axis to squeeze out which has size not equal to one\n'

In [162]:
np.squeeze(x, axis=2).shape

(1, 3)

## Changing kind of array

### 38 numpy.asarray
Convert the input to an array.

https://numpy.org/devdocs/reference/generated/numpy.asarray.html#numpy.asarray

In [163]:
a = [1, 2]
np.asarray(a)

array([1, 2])

### 39. asanyarray
Convert the input to an ndarray, but pass ndarray subclasses through. 

In [164]:
a = [1, 2]
np.asanyarray(a)

array([1, 2])

### 40.asmatrix
Interpret the input as a matrix.

In [165]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [166]:
m = np.asmatrix(x)
m

matrix([[1, 2],
        [3, 4]])

In [167]:
x[0,0] = 5
m

matrix([[5, 2],
        [3, 4]])

### 41. asscalar
Convert an array of size 1 to its scalar equivalent. 

In [168]:
np.asscalar(np.array([24]))

24

### 42. require
Return an ndarray of the provided type that satisfies requirements. 

In [169]:
x = np.arange(6).reshape(2,3)
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [170]:
y = np.require(x, dtype=np.float32, requirements=['A', 'O', 'W', 'F'])
y.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

## Joining arrays 

### 43. stack
Join a sequence of arrays along a new axis. 

In [171]:
arrays = [np.random.randn(3, 4) for _ in range(10)]
np.stack(arrays, axis=0).shape

(10, 3, 4)

In [172]:
np.stack(arrays, axis=1).shape

(3, 10, 4)

In [173]:
np.stack(arrays, axis=2).shape

(3, 4, 10)

In [174]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.stack((a, b))

array([[1, 2, 3],
       [2, 3, 4]])

In [175]:
np.stack((a, b), axis=-1)

array([[1, 2],
       [2, 3],
       [3, 4]])

### 44. column_stack(tup)
Stack 1-D arrays as columns into a 2-D array. 

In [176]:
a = np.array((1,2,3))
b = np.array((2,3,4))
np.column_stack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

### 45. d.stack(tup)
Stack arrays in sequence depth wise (along third axis). 

In [177]:
a = np.array((1,2,3))
b = np.array((2,3,4))
np.dstack((a,b))

array([[[1, 2],
        [2, 3],
        [3, 4]]])

In [178]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
np.dstack((a,b))

array([[[1, 2]],

       [[2, 3]],

       [[3, 4]]])

### 46. hstack (tup)
Stack arrays in sequence horizontally (column wise). 

In [179]:
a = np.array((1,2,3))
b = np.array((2,3,4))
np.hstack((a,b))

array([1, 2, 3, 2, 3, 4])

In [180]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

### 47. vstack(tup)
Stack arrays in sequence vertically (row wise). 

In [181]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [182]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4]])

### 48. block(arrays)
Assemble an nd-array from nested lists of blocks. 

In [183]:
A = np.eye(2) * 2
B = np.eye(3) * 3
np.block([[A,np.zeros((2, 3))],[np.ones((3, 2)), B]])

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [1., 1., 3., 0., 0.],
       [1., 1., 0., 3., 0.],
       [1., 1., 0., 0., 3.]])

In [184]:
np.block([1, 2, 3])

array([1, 2, 3])

## Splitting arrays

### 49. split
Split an array into multiple sub-arrays. 

In [185]:
x = np.arange(9.0)
np.split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

### 50. array_split
Split an array into multiple sub-arrays.

In [186]:
x = np.arange(8.0)
np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]

### 51. dsplit
Split array into multiple sub-arrays along the 3rd axis (depth). 

In [187]:
x = np.arange(16.0).reshape(2, 2, 4)
x

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])

In [188]:
np.dsplit(x, 2)

[array([[[ 0.,  1.],
         [ 4.,  5.]],
 
        [[ 8.,  9.],
         [12., 13.]]]), array([[[ 2.,  3.],
         [ 6.,  7.]],
 
        [[10., 11.],
         [14., 15.]]])]

In [189]:
np.dsplit(x, np.array([3, 6]))

[array([[[ 0.,  1.,  2.],
         [ 4.,  5.,  6.]],
 
        [[ 8.,  9., 10.],
         [12., 13., 14.]]]), array([[[ 3.],
         [ 7.]],
 
        [[11.],
         [15.]]]), array([], shape=(2, 2, 0), dtype=float64)]

### 52. hsplit
Split an array into multiple sub-arrays of equal size

In [190]:
x = np.arange(16.0).reshape(4, 4)

x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [191]:
np.hsplit(x, 2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]), array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

### 53. vsplit
Split an array into multiple sub-arrays vertically (row-wise).

In [192]:
x = np.arange(16.0).reshape(4, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [193]:
np.vsplit(x, 2)

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

In [194]:
np.vsplit(x, np.array([3, 6]))

[array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[12., 13., 14., 15.]]),
 array([], shape=(0, 4), dtype=float64)]

### 54. block (arrays)
Assemble an nd-array from nested lists of blocks.

In [195]:
A = np.eye(2) * 2
B = np.eye(3) * 3
np.block([[A,np.zeros((2, 3))],[np.ones((3, 2)), B]])

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [1., 1., 3., 0., 0.],
       [1., 1., 0., 3., 0.],
       [1., 1., 0., 0., 3.]])

## Splitting arrays

### 55. numpy.split
Split an array into multiple sub-arrays.

In [196]:
x = np.arange(9.0)
np.split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [197]:
x = np.arange(8.0)
np.split(x, [3, 5, 6, 10])

[array([0., 1., 2.]),
 array([3., 4.]),
 array([5.]),
 array([6., 7.]),
 array([], dtype=float64)]

### 56. numpy.array_split
Split an array into multiple sub-arrays.

In [198]:
x = np.arange(8.0)
np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]

In [199]:
x = np.arange(7.0)
np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4.]), array([5., 6.])]

### 57. numpy.dsplit
Split array into multiple sub-arrays along the 3rd axis (depth).

In [200]:
x = np.arange(16.0).reshape(2, 2, 4)
x

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])

In [201]:
np.dsplit(x, 2)

[array([[[ 0.,  1.],
         [ 4.,  5.]],
 
        [[ 8.,  9.],
         [12., 13.]]]), array([[[ 2.,  3.],
         [ 6.,  7.]],
 
        [[10., 11.],
         [14., 15.]]])]

In [202]:
np.dsplit(x, np.array([3, 6]))

[array([[[ 0.,  1.,  2.],
         [ 4.,  5.,  6.]],
 
        [[ 8.,  9., 10.],
         [12., 13., 14.]]]), array([[[ 3.],
         [ 7.]],
 
        [[11.],
         [15.]]]), array([], shape=(2, 2, 0), dtype=float64)]

### 58. hsplit (ary, indices_or_sections)
Split an array into multiple sub-arrays horizontally (column-wise).

In [203]:
x = np.arange(16.0).reshape(4, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [204]:
np.hsplit(x, 2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]), array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [205]:
np.hsplit(x, np.array([3, 6]))

[array([[ 0.,  1.,  2.],
        [ 4.,  5.,  6.],
        [ 8.,  9., 10.],
        [12., 13., 14.]]), array([[ 3.],
        [ 7.],
        [11.],
        [15.]]), array([], shape=(4, 0), dtype=float64)]

In [206]:
x = np.arange(8.0).reshape(2, 2, 2)
x

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

In [207]:
np.hsplit(x, 2)

[array([[[0., 1.]],
 
        [[4., 5.]]]), array([[[2., 3.]],
 
        [[6., 7.]]])]

### 59. vsplit (ary, indices_or_sections)
Split an array into multiple sub-arrays vertically (row-wise).

In [208]:
x = np.arange(16.0).reshape(4, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [209]:
np.vsplit(x, 2)

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

In [210]:
np.vsplit(x, np.array([3, 6]))

[array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[12., 13., 14., 15.]]),
 array([], shape=(0, 4), dtype=float64)]

In [211]:
x = np.arange(8.0).reshape(2, 2, 2)
x

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

In [212]:
np.vsplit(x, 2)

[array([[[0., 1.],
         [2., 3.]]]), array([[[4., 5.],
         [6., 7.]]])]

## Tiling arrays

### 60. tile (A, reps)

In [213]:
a = np.array([0, 1, 2])
np.tile(a, 2)

array([0, 1, 2, 0, 1, 2])

In [214]:
np.tile(a, (2, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [215]:
b = np.array([[1, 2], [3, 4]])
np.tile(b, 2)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [216]:
np.tile(b, (2, 1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [217]:
c = np.array([1,2,3,4])
np.tile(c,(4,1))

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

### 61. repeat (a, repeats[, axis])
Repeat elements of an array.

In [218]:
np.repeat(3, 4)

array([3, 3, 3, 3])

In [219]:
x = np.array([[1,2],[3,4]])
np.repeat(x, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [220]:
np.repeat(x, 3, axis=1)

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [221]:
np.repeat(x, [1, 2], axis=0)

array([[1, 2],
       [3, 4],
       [3, 4]])

## Adding and removing elements

### 62. delete (arr, obj[, axis])
Return a new array with sub-arrays along an axis deleted.

In [222]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [223]:
np.delete(arr, 1, 0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [224]:
np.delete(arr, np.s_[::2], 1)

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

### 63. insert (arr, obj, values[, axis])
Insert values along the given axis before the given indices.

In [225]:
a = np.array([[1, 1], [2, 2], [3, 3]])
a

array([[1, 1],
       [2, 2],
       [3, 3]])

In [226]:
np.insert(a, 1, 5)

array([1, 5, 1, 2, 2, 3, 3])

In [227]:
np.insert(a, 1, 5, axis=1)

array([[1, 5, 1],
       [2, 5, 2],
       [3, 5, 3]])

## Rearranging elements

### 64. flip (m[, axis])
Reverse the order of elements in an array along the given axis.

In [228]:
A = np.arange(8).reshape((2,2,2))
A

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [229]:
np.flip(A, 0)

array([[[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

In [230]:
np.flip(A, 1)

array([[[2, 3],
        [0, 1]],

       [[6, 7],
        [4, 5]]])

In [231]:
np.flip(A, 1)

array([[[2, 3],
        [0, 1]],

       [[6, 7],
        [4, 5]]])

In [232]:
np.flip(A, 1)

array([[[2, 3],
        [0, 1]],

       [[6, 7],
        [4, 5]]])

In [233]:
A = np.random.randn(3,4,5)

In [234]:
np.all(np.flip(A,2) == A[:,:,::-1,...])

True

### 65. flipud (m)
Flip array in the up/down direction.

In [235]:
A = np.diag([1.0, 2, 3])
A

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [236]:
np.flipud(A)

array([[0., 0., 3.],
       [0., 2., 0.],
       [1., 0., 0.]])

In [237]:
A = np.random.randn(2,3,5)
A

array([[[-1.77048011, -0.61269371, -1.45350012,  0.17145607,
          1.07112494],
        [ 1.60238639,  0.20825982, -0.08543325,  0.04235161,
         -2.10755022],
        [-1.31648872,  0.39687088,  1.06617112, -0.9812338 ,
          1.19977502]],

       [[-1.08057953, -0.42779444, -0.34395003,  1.52159915,
          0.07363209],
        [ 0.07809601,  2.9682354 ,  0.14086447,  0.4776486 ,
         -0.58358071],
        [ 1.00267276,  1.65532427,  1.95693704,  0.70613827,
         -0.72144216]]])

In [238]:
np.all(np.flipud(A) == A[::-1,...])

True

In [239]:
np.flipud([1,2])

array([2, 1])

# Binary operations
https://numpy.org/devdocs/reference/routines.bitwise.html

## Elementwise bit operations

### 66. bitwise_and(x1, x2, /[, out, where, …])
Compute the bit-wise AND of two arrays element-wise.

In [240]:
np.bitwise_and(13, 17)

1

In [241]:
np.bitwise_and(14, 13)

12

In [242]:
np.binary_repr(12)

'1100'

### 67. bitwise_or(x1, x2, /[, out, where, casting, …])

In [243]:
np.bitwise_or(13, 16)

29

In [244]:
np.binary_repr(29)

'11101'

In [245]:
np.bitwise_or(32, 2)

34

In [246]:
np.bitwise_or([33, 4], 1)

array([33,  5], dtype=int32)

In [247]:
np.bitwise_or([33, 4], [1, 2])

array([33,  6], dtype=int32)

# String operations

## String operations

### 68. numpy.char.capitalize
Return a copy of a with only the first character of each element capitalized.

In [248]:
c = np.array(['a1b2','1b2a','b2a1','2a1b'],'S4'); c

array([b'a1b2', b'1b2a', b'b2a1', b'2a1b'], dtype='|S4')

## Comparison

### 69. equal(x1, x2)
Return (x1 == x2) element-wise.

In [249]:
A = np.diag(["1.0", "2", "3"])
B = np.diag(["1.0", "2", "3"])

In [250]:
np.char.equal(A,B)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## String information

### 70. count(a, sub[, start, end])
Returns an array with the number of non-overlapping occurrences of substring sub in the range [start, end].

In [251]:
c = np.array(['aAaAaA', '  aA  ', 'abBABba'])
c

array(['aAaAaA', '  aA  ', 'abBABba'], dtype='<U7')

In [252]:
np.char.count(c, 'A')

array([3, 1, 1])

In [253]:
np.char.count(c, 'aA')

array([3, 1, 0])

In [254]:
np.char.count(c, 'A', start=1, end=4)

array([2, 1, 1])

In [255]:
np.char.count(c, 'A', start=1, end=3)

array([1, 0, 0])

### 71. replace(a, old, new[, count])

In [256]:
print(np.char.replace ('He is a good boy', 'is', 'was'))

He was a good boy


### 72. rfind(a, sub[, start, end])
For each element in a, return the highest index in the string where substring sub is found, such that sub is contained within [start, end].

In [257]:
x = np.char.rfind('The Quick Brown Fox', 'Fox', start=0, end=None)
x

array(16)

## Convenience class

### 73. chararray(shape[, itemsize, unicode, …])
Provides a convenient view on arrays of string and unicode values.

In [258]:
charar = np.chararray((3, 3))
charar

chararray([[b'\x10', '', ''],
           ['', '', ''],
           ['', '', b'\xff']], dtype='|S1')

In [259]:
charar[:] = 'a'
charar

chararray([[b'a', b'a', b'a'],
           [b'a', b'a', b'a'],
           [b'a', b'a', b'a']], dtype='|S1')

In [260]:
charar = np.chararray(charar.shape, itemsize=5)
charar

chararray([['', '', ''],
           ['', '', ''],
           ['', '', '']], dtype='|S5')

In [261]:
charar[:] = 'abc'
charar

chararray([[b'abc', b'abc', b'abc'],
           [b'abc', b'abc', b'abc'],
           [b'abc', b'abc', b'abc']], dtype='|S5')


2.Crear un ejemplo de cómo guardar y cargar arreglos de un archivo binario .npy y .npz:
•NumPy binary files (NPY, NPZ)


#### Guardar y cargar NPY

In [262]:
guardar = np.array(("Esta","es","una","prueba"))
np.save('NPY',guardar)

In [263]:
cargar=np.load('NPY.npy')
cargar

array(['Esta', 'es', 'una', 'prueba'], dtype='<U6')

#### Guardar y cargar NPZ

In [264]:
guardar_1 = np.array(("Esta","es","una","prueba"))
guardar_2 = np.array((1,2,3,4))
np.savez('NPZ', x= guardar_1, y=guardar_2 )

In [265]:
cargar = np.load('NPZ.npz')
cargar ["x"]

array(['Esta', 'es', 'una', 'prueba'], dtype='<U6')

In [266]:
cargar ["y"]

array([1, 2, 3, 4])

3.Crear un ejemplo de cómo guardar y cargar arreglos de un archivo de texto .txt:
•NumPy Text files 






In [267]:
arreglo_1 = np.arange(100).reshape(10,10)
np.savetxt('Ejemplo_txt', arreglo_1, delimiter=',')  

In [268]:
arreglo_1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [269]:
np.loadtxt('Ejemplo_txt', delimiter=',')

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
       [50., 51., 52., 53., 54., 55., 56., 57., 58., 59.],
       [60., 61., 62., 63., 64., 65., 66., 67., 68., 69.],
       [70., 71., 72., 73., 74., 75., 76., 77., 78., 79.],
       [80., 81., 82., 83., 84., 85., 86., 87., 88., 89.],
       [90., 91., 92., 93., 94., 95., 96., 97., 98., 99.]])

4.Crear una función llamada estimacionMCO que lea un archivo CSV con 7 columnas, que corresponden a las variables (𝑥 1𝑖 ,…,𝑥 6𝑖 ) 
(x1i,…,x6i)
 y 𝑦 𝑖  
yi
. 

•La función debe computar matricialmente los parámetros del modelo de regresión lineal: 𝑦=𝑋𝛽 
y=Xβ
. 


•Estos parámetros deben ser devueltos como un arreglo de NumPy. 


•Utilice la función de lectura de archivos de NumPy.


In [270]:
def estimacionMCO():
    file=str(input("Ingrese variables Xi y Y: "))+".csv"
    variables=np.genfromtxt(file,delimiter=',',skip_header=1)
    x=variables[: , :6]
    y=variables[:,6:7]
    x_=(x.T)@x
    y_=(x.T)@y
    betas=((np.linalg.inv(x_))@y_)
    return betas

In [271]:
estimacionMCO()

Ingrese variables Xi y Y: MCO


array([[ 17.94689558],
       [208.51096939],
       [402.18926051],
       [262.93394203],
       [-92.08598688],
       [112.9148541 ]])